name: active_particles_env
channels:
  - glotzer
  - conda-forge
dependencies:
  - python=3.6
  - gsd=1.5.*
  - hoomd=2.2.*
  - matplotlib=2.1.*
  - numpy=1.14.*
  - scipy=1.0*
  - ovito=2.9.*
  - pyqt=5.*
